import type {
  GenerationJob,
  ComposedPackage,
  ComposedFile,
  TemplateManifest,
  SkillManifest,
  IntegrationManifest,
  AgentTarget,
} from "@/types";
import { stringify as yamlStringify } from "yaml";
import { getTemplate, getSkills, getIntegrations } from "@/lib/registry";
import { AGENT_TARGET_FILES } from "@/lib/agent-targets";

function buildSystemPrompt(skills: SkillManifest[]): string {
  if (skills.length === 0) return "You are a helpful AI assistant.";
  const sections = skills.map((skill) => `## ${skill.title}\n\n${skill.personaText}`);
  return sections.join("\n\n---\n\n");
}

function buildReadme(
  template: TemplateManifest,
  skills: SkillManifest[],
  integrations: IntegrationManifest[],
  job: GenerationJob,
): string {
  const skillList = skills.map((s) => `- **${s.title}**: ${s.description}`).join("\n");
  const integrationList = integrations
    .map((index) => `- **${index.name}**: ${index.description}`)
    .join("\n");
  return `# ${job.projectName}

> Generated by AgentFoundry

## Template

**${template.name}** — ${template.description}

## Skills

${skillList || "No skills selected."}

## Integrations

${integrationList || "No integrations selected."}

## Agent Target

${job.agentTarget}

## Quick Start

\`\`\`bash
./setup.sh
\`\`\`

Or on Windows:

\`\`\`powershell
.\\setup.ps1
\`\`\`
`;
}

function buildAgentsFile(skills: SkillManifest[], template: TemplateManifest): string {
  const skillSections = skills
    .map((skill) => `## ${skill.title}\n\n${skill.personaText}`)
    .join("\n\n---\n\n");
  const skillReference =
    skills.length > 0
      ? `\n\nIndividual skill definitions with full rules and references are in the \`skills/\` directory.`
      : "";
  return `# AGENTS.md

This file describes the AI agent configuration for **${template.name}**.${skillReference}

${skillSections || "No skills configured."}
`;
}

function buildSkillFileContent(skill: SkillManifest): string {
  const frontmatter = yamlStringify({
    name: skill.id,
    description: skill.description,
    tags: skill.tags,
    compatibility: skill.compatibility,
  }).trimEnd();
  return `---\n${frontmatter}\n---\n\n# ${skill.title}\n\n## Overview\n\nKeywords: ${skill.tags.join(", ")}\n\n## Instructions\n\n${skill.personaText}\n\n## When to Use This Skill\n\n- User needs help with: ${skill.tags.join(", ")}\n- Compatible with: ${skill.compatibility.join(", ")} projects\n`;
}

function buildMcpConfig(integrations: IntegrationManifest[]): string {
  const servers: Record<string, { command: string; args: string[] }> = {};
  for (const integration of integrations) {
    for (const server of integration.mcpServers) {
      servers[server.name] = {
        command: "npx",
        args: ["-y", server.package],
      };
    }
  }
  return JSON.stringify({ mcpServers: servers }, null, 2);
}

function buildEnvironmentExample(integrations: IntegrationManifest[]): string {
  const allVariables = integrations.flatMap((index) => index.envVars);
  const uniqueVariables = [...new Set(allVariables)];
  if (uniqueVariables.length === 0) return "# .env.example\n# No environment variables required.\n";
  const lines = uniqueVariables.map((variable) => `${variable}=`);
  return `# .env.example\n# Copy this file to .env and fill in the values.\n\n${lines.join("\n")}\n`;
}

function buildSetupSh(job: GenerationJob, template: TemplateManifest): string {
  const isPython = template.stack.toLowerCase().includes("python");
  const installCmd = isPython ? "pip install -r requirements.txt" : "npm install";
  const developmentCmd = isPython ? "python main.py" : "npm run dev";
  const prereqCheck = isPython
    ? `# Check Python + pip
if ! command -v python3 &>/dev/null; then
  echo "❌  python3 is required but not found."
  echo "    Install it from https://www.python.org/downloads/"
  exit 1
fi
if ! command -v pip &>/dev/null && ! command -v pip3 &>/dev/null; then
  echo "❌  pip is required but not found."
  echo "    Run: python3 -m ensurepip --upgrade"
  exit 1
fi`
    : `# Check Node.js + npm
if ! command -v node &>/dev/null; then
  echo "❌  Node.js is required but not found."
  echo "    Install it from https://nodejs.org  (LTS recommended)"
  exit 1
fi
if ! command -v npm &>/dev/null; then
  echo "❌  npm is required but not found."
  echo "    It ships with Node.js — reinstall from https://nodejs.org"
  exit 1
fi
NODE_VER=$(node --version | cut -c2- | cut -d. -f1)
if [ "$NODE_VER" -lt 18 ]; then
  echo "⚠️   Node.js 18+ is recommended (found $(node --version))."
fi`;

  return `#!/usr/bin/env bash
# =============================================================================
#  setup.sh — ${job.projectName}
#  Generated by AgentFoundry
# =============================================================================
#
#  USAGE
#  -----
#  Make the script executable, then run it:
#
#    chmod +x setup.sh
#    ./setup.sh
#
#  Or run directly without changing permissions:
#
#    bash setup.sh
#
#  WHAT THIS SCRIPT DOES
#  ----------------------
#  1. Verifies required tools are installed
#  2. Copies .env.example → .env  (skipped if .env already exists)
#  3. Installs project dependencies
#  4. Prints next-step instructions
#
#  REQUIREMENTS
#  ------------
#  ${isPython ? "- Python 3.9+\n#  - pip" : "- Node.js 18+\n#  - npm 9+"}
#  - Git (optional but recommended)
#
# =============================================================================
set -euo pipefail

# ── Colours (disabled when not a TTY) ----------------------------------------
if [ -t 1 ]; then
  BOLD="\\033[1m"; GREEN="\\033[32m"; YELLOW="\\033[33m"; RED="\\033[31m"; RESET="\\033[0m"
else
  BOLD=""; GREEN=""; YELLOW=""; RED=""; RESET=""
fi

step() { echo -e "$BOLD\\n> $*$RESET"; }
ok()   { echo -e "$GREEN  ok: $*$RESET"; }
warn() { echo -e "$YELLOW  warn: $*$RESET"; }

echo -e "$BOLD=============================="
echo -e " ${job.projectName} — setup"
echo -e "==============================$RESET"

# ── Step 1: Check prerequisites -----------------------------------------------
step "Checking prerequisites…"
${prereqCheck}
ok "Prerequisites satisfied."

# ── Step 2: Environment file --------------------------------------------------
step "Setting up environment…"
if [ -f .env ]; then
  warn ".env already exists — skipping copy. Review it to make sure all keys are set."
else
  cp .env.example .env
  ok "Created .env from .env.example"
  echo "   ➜  Open .env and fill in your API keys before running the app."
fi

# ── Step 3: Install dependencies ----------------------------------------------
step "Installing dependencies…"
${installCmd}
ok "Dependencies installed."

# ── Done ---------------------------------------------------------------------
echo ""
echo -e "$GREEN$BOLD  Setup complete!$RESET"
echo ""
echo "Next steps:"
echo "  1. Edit .env with your API keys (OPENAI_API_KEY, etc.)"
echo "  2. Review AGENTS.md — your agent instructions and persona configuration"
echo "  3. Review mcp.json — MCP server configuration"
echo "     Start MCP servers with:  npx -y @modelcontextprotocol/server-filesystem /path/to/dir"
echo "  4. Start the app:"
echo "       ${developmentCmd}"
echo ""
echo "  See README.md for full documentation."
`;
}

function buildSetupPs1(job: GenerationJob, template: TemplateManifest): string {
  const isPython = template.stack.toLowerCase().includes("python");
  const installCmd = isPython ? "pip install -r requirements.txt" : "npm install";
  const developmentCmd = isPython ? "python main.py" : "npm run dev";
  const prereqCheck = isPython
    ? `# Check Python
try { $null = python --version 2>&1 } catch {
  Write-Error "python is required but not found. Install from https://www.python.org/downloads/"
  exit 1
}
# Check pip
try { $null = pip --version 2>&1 } catch {
  Write-Error "pip is required. Run: python -m ensurepip --upgrade"
  exit 1
}`
    : `# Check Node.js
try { $null = node --version 2>&1 } catch {
  Write-Error "Node.js is required but not found. Install from https://nodejs.org"
  exit 1
}
$nodeVer = [int]((node --version).TrimStart('v').Split('.')[0])
if ($nodeVer -lt 18) {
  Write-Warning "Node.js 18+ is recommended (found $(node --version))."
}
# Check npm
try { $null = npm --version 2>&1 } catch {
  Write-Error "npm is required. It ships with Node.js — reinstall from https://nodejs.org"
  exit 1
}`;

  return `# =============================================================================
#  setup.ps1 — ${job.projectName}
#  Generated by AgentFoundry
# =============================================================================
#
#  USAGE
#  -----
#  Open PowerShell (Windows) or pwsh (macOS/Linux) and run:
#
#    .\\setup.ps1
#
#  If you see an execution-policy error on Windows, run this first:
#    Set-ExecutionPolicy -Scope CurrentUser -ExecutionPolicy RemoteSigned
#
#  Or bypass for a single run:
#    powershell -ExecutionPolicy Bypass -File .\\setup.ps1
#
#  WHAT THIS SCRIPT DOES
#  ----------------------
#  1. Verifies required tools are installed
#  2. Copies .env.example -> .env  (skipped if .env already exists)
#  3. Installs project dependencies
#  4. Prints next-step instructions
#
#  REQUIREMENTS
#  ------------
#  ${isPython ? "- Python 3.9+\n#  - pip" : "- Node.js 18+\n#  - npm 9+"}
#  - PowerShell 5.1+ (Windows) or pwsh 7+ (macOS/Linux)
#
# =============================================================================
$ErrorActionPreference = "Stop"

function Write-Step  { param($msg) Write-Host ""; Write-Host ">> $msg" -ForegroundColor Cyan }
function Write-Ok    { param($msg) Write-Host "OK $msg"  -ForegroundColor Green }
function Write-Warn  { param($msg) Write-Host "!! $msg"  -ForegroundColor Yellow }

Write-Host "=============================="
Write-Host " ${job.projectName} — setup"
Write-Host "=============================="

# ── Step 1: Check prerequisites -----------------------------------------------
Write-Step "Checking prerequisites…"
${prereqCheck}
Write-Ok "Prerequisites satisfied."

# ── Step 2: Environment file --------------------------------------------------
Write-Step "Setting up environment…"
if (Test-Path .env) {
  Write-Warn ".env already exists — skipping copy. Review it to make sure all keys are set."
} else {
  Copy-Item .env.example .env
  Write-Ok "Created .env from .env.example"
  Write-Host "   -> Open .env and fill in your API keys before running the app."
}

# ── Step 3: Install dependencies ----------------------------------------------
Write-Step "Installing dependencies…"
${installCmd}
Write-Ok "Dependencies installed."

# ── Done ---------------------------------------------------------------------
Write-Host ""
Write-Host "✅  Setup complete!" -ForegroundColor Green
Write-Host ""
Write-Host "Next steps:"
Write-Host "  1. Edit .env with your API keys (OPENAI_API_KEY, etc.)"
Write-Host "  2. Review AGENTS.md — your agent instructions and persona configuration"
Write-Host "  3. Review mcp.json — MCP server configuration"
Write-Host "     Start an MCP server:  npx -y @modelcontextprotocol/server-filesystem C:\\path\\to\\dir"
Write-Host "  4. Start the app:"
Write-Host "       ${developmentCmd}"
Write-Host ""
Write-Host "  See README.md for full documentation."
`;
}

function buildStarterYaml(job: GenerationJob): string {
  return `# starter.yaml — reproducibility manifest
projectName: ${job.projectName}
templateId: ${job.templateId}
agentTarget: ${job.agentTarget}
scriptType: ${job.scriptType}
skillIds:
${job.skillIds.map((id) => `  - ${id}`).join("\n") || "  []"}
integrationIds:
${job.integrationIds.map((id) => `  - ${id}`).join("\n") || "  []"}
generatedAt: ${new Date().toISOString()}
`;
}

function buildAgentTargetFile(
  agentTarget: AgentTarget,
  systemPrompt: string,
): ComposedFile | undefined {
  const filePath = AGENT_TARGET_FILES[agentTarget];
  if (!filePath) return undefined;
  return {
    path: filePath,
    content: `# Agent Instructions\n\n${systemPrompt}\n`,
  };
}

export function compose(job: GenerationJob): ComposedPackage {
  const template = getTemplate(job.templateId);
  if (!template) throw new Error(`Unknown template: ${job.templateId}`);

  const selectedSkills = getSkills(job.skillIds, job.extraSkills ?? []);
  const selectedIntegrations = getIntegrations(job.integrationIds);
  const systemPrompt = buildSystemPrompt(selectedSkills);

  const files: ComposedFile[] = [
    {
      path: "README.md",
      content: buildReadme(template, selectedSkills, selectedIntegrations, job),
    },
    { path: "AGENTS.md", content: buildAgentsFile(selectedSkills, template) },
    ...selectedSkills.map((skill) => ({
      path: `skills/${skill.id}/SKILL.md`,
      content: buildSkillFileContent(skill),
    })),
    { path: ".env.example", content: buildEnvironmentExample(selectedIntegrations) },
    { path: "mcp.json", content: buildMcpConfig(selectedIntegrations) },
    { path: "setup.sh", content: buildSetupSh(job, template) },
    { path: "setup.ps1", content: buildSetupPs1(job, template) },
    { path: "starter.yaml", content: buildStarterYaml(job) },
  ];

  const agentFile = buildAgentTargetFile(job.agentTarget, systemPrompt);
  if (agentFile) files.push(agentFile);

  return { files, systemPrompt };
}
