import type { NextRequest } from "next/server";
import JSZip from "jszip";
import { z } from "zod";
import { getSkillStore } from "@/lib/skill-store";
import { getSkillFileBinding } from "@/lib/skill-bindings";
import { checkApiKey } from "@/lib/auth";

const BodySchema = z.object({
  skillIds: z.array(z.string().min(1)).min(1).max(50),
});

function buildInstallGuide(skillTitles: string[]): string {
  return [
    "# Skill Pack — Installation Guide",
    "",
    "This ZIP was generated by **AgentFoundry**.",
    "",
    "## Contents",
    "",
    ...skillTitles.map((t) => `- ${t}`),
    "",
    "## How to install",
    "",
    "1. Copy the `skills/` folder from this ZIP into the root of your project:",
    "   ```",
    "   your-project/",
    "   └── skills/",
    "       ├── clean-code-ddd/",
    "       │   └── SKILL.md",
    "       └── ...",
    "   ```",
    "",
    "2. Reference each skill from your `AGENTS.md`:",
    "   ```markdown",
    "   <!-- AGENTS.md -->",
    "   # Agent Instructions",
    "   ",
    "   See skills/ for individual skill packs.",
    "   ```",
    "",
    "3. Or paste the `## Instructions` section from each SKILL.md directly",
    "   into the `instructions=` field of your `Agent()` call:",
    "   ```python",
    "   from agents import Agent",
    "   ",
    "   with open('skills/clean-code-ddd/SKILL.md') as f:",
    "       instructions = f.read()",
    "   ",
    "   agent = Agent(name='CodeReviewer', instructions=instructions)",
    "   ```",
    "",
    "## Learn more",
    "",
    "- [OpenAI Agents SDK](https://openai.com/index/the-next-evolution-of-the-agents-sdk/)",
    "- [AgentFoundry](https://github.com/agentfoundry)",
    "",
  ].join("\n");
}

/** POST /api/skills/download — returns a ZIP of selected SKILL.md files */
export async function POST(request: NextRequest) {
  const auth = checkApiKey(request);
  if (!auth.authorized) {
    return Response.json({ error: "Unauthorized", message: auth.reason }, { status: 401 });
  }

  let body: unknown;
  try {
    body = await request.json();
  } catch {
    return Response.json({ error: "Invalid JSON body" }, { status: 400 });
  }

  const parsed = BodySchema.safeParse(body);
  if (!parsed.success) {
    return Response.json(
      { error: parsed.error.issues[0]?.message ?? "Invalid request" },
      { status: 400 },
    );
  }

  const { skillIds } = parsed.data;
  const store = getSkillStore();
  const binding = getSkillFileBinding();

  const skills = await Promise.all(skillIds.map(async (id) => store.get(id)));

  const found = skills.filter(Boolean);
  if (found.length === 0) {
    return Response.json({ error: "None of the requested skills were found" }, { status: 404 });
  }

  const zip = new JSZip();

  for (const skill of found) {
    if (!skill) continue;
    const content = await binding.readFile(skill.id);
    if (content) zip.file(`skills/${skill.id}/SKILL.md`, content);
  }

  zip.file("INSTALL.md", buildInstallGuide(found.filter(Boolean).map((s) => s!.title)));

  const zipBuffer = await zip.generateAsync({ type: "nodebuffer", compression: "DEFLATE" });

  return new Response(new Uint8Array(zipBuffer), {
    headers: {
      "Content-Type": "application/zip",
      "Content-Disposition": `attachment; filename="skills.zip"`,
    },
  });
}
